### ISSUE TITLE
App crashes when setting custom background

### ISSUE THREAD

**Issue by tyler-hitzeman** [focus-launcher/focus-launcher-android#15]
This was identified by zed13 while he was working on #14. Creating issue so more details can be added here for future triaging.

**Comment by zed13** [comment]
For some reason app stops crashing when user changes wallpapper. Nevertheless, it's impossible to set custom background. 

1. Go to intention screen.
2. Tap 3-dots button
3. Select settings.
4. Go to `Customize appearance`
5. Turn on `Custom background image` switch (here app may crash)
6. Grant access for storage 
7. Choose picture

Expected result: background image is changed
Actual result: Nothing happened

There is exception in logs:
```
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=android:fragment:2, request=10, result=-1, data=Intent { flg=0x1 hwFlg=0x10 (has extras) }} to activity {co.siempo.phone/co.siempo.phone.activities.SettingsActivity_}: java.lang.IllegalArgumentException: Invalid URI: content://media/external/images/media/29319
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5471)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5512)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
     Caused by: java.lang.IllegalArgumentException: Invalid URI: content://media/external/images/media/29319
        at android.provider.DocumentsContract.getDocumentId(DocumentsContract.java:1225)
        at co.siempo.phone.fragments.TempoHomeFragment.onActivityResult(TempoHomeFragment.java:414)
        at android.app.Activity.dispatchActivityResult(Activity.java:8440)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5464)
```

**Comment by tyler-hitzeman** [comment]
It seems like this only occurs when selecting an image that isn't already on the phone.
- When selecting a picture from my Google Photos, I replicated this error
- However, when selecting one from my camera roll or recent images, it worked.

**Comment by zed13** [comment]
@tyler-hitzeman, please provide specs of test device: manufacturer and Android version

**Comment by tyler-hitzeman** [comment]
@zed13 Updated original comment with specs. 

It worked for #13, but I'm getting the same thing you saw when trying out the latest APK from #19: nothing happens after selecting the picture (even one that is already on the device)

**Comment by tyler-hitzeman** [comment]
The custom background feature was made less stable after #19 (#20).  

@zed13 is going to try fixing the issue. If it's easy enough to fix and update by end of this week, he'll do so. If not, we'll just remove the option from the menu and circle back after the app is in the Play Store

**Comment by zed13** [comment]
I picked it up
