### ISSUE TITLE
Remove Email List Screen

### ISSUE THREAD

**Issue by tyler-hitzeman** [focus-launcher/focus-launcher-android#23]
When installing, a screen prompts user to provide their email. I'm not sure where this data is stored, but that database of emails is no longer accessible to us (since Siempo dissolved). 

- Find out what happens to emails after the user provides them. (Is the address send in a POST request to a Mailchimp endpoint, for example?)
- Look into how difficult it'd be to change where those emails go. If it's easy, I can setup a new list and then we can direct emails there. If it's too complicated, we can put this off until after the initial launch
- Post your findings here

**Comment by zed13** [comment]
It sends address to the Firebase. So, we got exception when tried to send email to Firebase:
```
java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process io.focuslauncher. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(Unknown Source:55)
        at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source:0)
        at co.siempo.phone.activities.EmailRequestActivity.storeDataToFirebase(EmailRequestActivity.java:181)
        at co.siempo.phone.activities.EmailRequestActivity.sendEvent(EmailRequestActivity.java:166)
        at co.siempo.phone.activities.EmailRequestActivity.onClick(EmailRequestActivity.java:143)
        at android.view.View.performClick(View.java:7192)
        at android.view.View.performClickInternal(View.java:7166)
        at android.view.View.access$3500(View.java:824)
        at android.view.View$PerformClick.run(View.java:27592)
        at android.os.Handler.handleCallback(Handler.java:888)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:213)
        at android.app.ActivityThread.main(ActivityThread.java:8178)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```
And `FirebaseApp.initializeApp(Context)` has never been called. Block which sends saves the email is surrounded with try {} catch {}. Who knows how long it doesn't work...

**Comment by tyler-hitzeman** [comment]
Interesting, wonder how long it hasn't been working for. In any case, I agree that it's not necessary. 

Are you OK with creating a PR to remove the email request screen entirely?

**Comment by zed13** [comment]
OK
